name: Tontine

on:
  push:
    branches: [ "main" ]

jobs:
  # create-flodfolderer:
  #   name: create-folder
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Create folder on Virtual Machine
  #     uses: appleboy/ssh-action@v1.0.0
  #   - name: Set up JDK 21
  #     uses: actions/setup-java@v4
  #     with:
  #       host: ${{  }}
  #       usrname: ${{  }}
  #       pasword: ${{  }}
  #       port: ${{  }}
  #       run: mvn -B package --file pom.xml

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: aaaaaaa
          POSTGRES_DB: tontine
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Configurer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Install PostgreSQL
        run: sudo apt-get install postgresql-client -y
      
      - name: Attendre que PostgreSQL soit prêt
        env:
          PGPASSWORD: aaaaaaa
        run: |
          psql -h localhost -p 5433 -U postgres -d tontine -f src\main\resources\init.sql;

      - name: Exécuter les tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/tontine?currentSchema=global_schema
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: aaaaaaa
        run: mvn clean package